apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: olu-certificate
  namespace: sock-shop
spec:
  secretName: olu-secret
  issuerRef: 
    name: olu-issuer
    kind: ClusterIssuer
  commonName: www.holumyde.store
  dnsNames:
  - www.holumyde.store